[package]
name = "scrape"
version = "0.1.0"
authors = ["Roman Frołow <rofrol@gmail.com>"]

[dependencies]
reqwest = "0.8.4"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
env_logger = "0.5"
error-chain = "0.10"